### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by mmck345** [pau1adam/CurrentActivity#5]
![image](https://user-images.githubusercontent.com/52917429/151704184-75232093-2620-43fd-aa22-7926804a673a.png)
![image](https://user-images.githubusercontent.com/52917429/151704203-80ddfdcc-a5c9-44c5-903f-9f33c9567001.png)

It returns **null** to me.

I would be very happy for your help
Thank you!

**Comment by pau1adam** [comment]
Hi!

It looks like you added a custom Application class inside your Activity.
Your _**App**_ class should be an entirely separate class.

After you separate the classes you will also have to register your Application class in the AndroidManifest.xml file. 
Click [here](https://stackoverflow.com/questions/2929562/register-application-class-in-manifest) if you don't know how!
